name: Deploy Pages
on:
  push:
    branches:
      - main
jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
      - name: Install base dependencies
        run: |
          uv pip install --upgrade pip
      - name: Install all dependencies
        run: |
          uv pip install -r requirements.txt
      - name: Run notebooks and copy to temp
        run: |
          jupyter nbconvert --output-dir='~/tmp' --execute --to markdown *.ipynb
          git checkout gh-pages
          cp -r ~/tmp/* ./notebooks-rendered
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        if: success()
        with:
          push_options: '--force'
          commit_options: '--no-verify --amend'
          commit_author: GitHub Actions <actions@github.com>
          commit_message: Update tutorial page