name: Run Jupyter Notebook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        
    - name: Install dependencies
      run: |
        uv pip install -r requirements.txt
        uv pip install jupyter nbconvert
        
    - name: Execute notebook
      run: |
        jupyter nbconvert --to notebook --execute jax-diffusion-models-pydata-boston-2025.ipynb --output jax-diffusion-models-pydata-boston-2025-executed.ipynb 